spring:
  profiles:
    active: dev
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

mybatis_config_file: mybatis-config.xml
mapper_path: /mapper/**.xml
entity_package: com.xl.backen.entity