server:
  port: 8093

jdbc:
  driver: com.mysql.jdbc.Driver
  url: jdbc:mysql://localhost:3306/cloudcity?userUnicode=true&characterEncoding=utf-8&useSSL=false
  username: root
  password: 123456

filePath:   F:/work/tup/
nginxPath:  http://localhost:8060/tup/